import { Injectable } from '@angular/core';
import { Casa } from '../app/models/modelCasa';

@Injectable({
  providedIn: 'root'
})
export class CasasController {

  private casas: Casa[] = [
    {
      titulo: "Chalet independiente con piscina",
      direccion: "Camino Viejo de Talavera, 12",
      ciudad: "Talavera",
      provincia: "Toledo",
      cp: "45600",
      pais: "España",
      lat: 39.95851,
      lng: -4.83256,
      precio: 295000,
      precioM2: 1475,
      antiguedad: 9,
      tipo: "Independiente",
      plantas: 1,
      metrosConstruidos: 200,
      terreno: 10000,
      habitaciones: 5,
      banos: 3,
      descripcion: "Hermoso chalet independiente con piscina y jardín privado. Situado en una zona tranquila con excelentes vistas. Perfecto para familias que buscan tranquilidad y comodidad.",
      orientacion: "Sur",
      anoConstruccion: 2015,
      estado: "Excelente estado",
      extras: ["Piscina", "Jardín", "Garaje", "Trastero"],
      imagenes: ["assets/img/inicio1.jpeg", "assets/img/inicio2.jpeg", "assets/img/inicio3.jpeg"]
    },
    {
      titulo: "Finca de regadío con buen acceso",
      direccion: "EX384, km 12",
      ciudad: "Madrigal de la Vera",
      provincia: "Cáceres",
      cp: "10400",
      pais: "España",
      lat: 40.10123,
      lng: -5.63645,
      precio: 150000,
      precioM2: 4.29,
      antiguedad: 0,
      tipo: "Finca",
      plantas: 0,
      metrosConstruidos: 0,
      terreno: 35000,
      habitaciones: 0,
      banos: 0,
      descripcion: "Finca de regadío con buen acceso en zona de vega, llana, vallada y con luz. Edificabilidad permitida de vivienda unifamiliar aislada supeditada a explotación agropecuaria.",
      orientacion: "N/A",
      anoConstruccion: 0,
      estado: "Parcela disponible",
      extras: ["Agua corriente", "Electricidad", "Vallado"],
      imagenes: ["assets/img/inicio4.jpeg", "assets/img/inicio5.jpeg"]
    },
    {
      titulo: "Ático moderno en el centro",
      direccion: "Calle Mayor, 45",
      ciudad: "Madrid",
      provincia: "Madrid",
      cp: "28013",
      pais: "España",
      lat: 40.4168,
      lng: -3.7038,
      precio: 450000,
      precioM2: 5000,
      antiguedad: 2,
      tipo: "Ático",
      plantas: 1,
      metrosConstruidos: 90,
      terreno: 0,
      habitaciones: 3,
      banos: 2,
      descripcion: "Ático luminoso y moderno en el corazón de Madrid. Terraza privada con vistas panorámicas. Reformado recientemente con materiales de alta calidad.",
      orientacion: "Sur-Este",
      anoConstruccion: 2022,
      estado: "Nuevo",
      extras: ["Terraza", "Ascensor", "Trastero", "Parking"],
      imagenes: ["assets/img/inicio6.jpeg", "assets/img/inicio7.jpeg", "assets/img/inicio8.jpeg"]
    },
    {
      titulo: "Villa de lujo con jardín",
      direccion: "Avenida del Mar, 8",
      ciudad: "Marbella",
      provincia: "Málaga",
      cp: "29600",
      pais: "España",
      lat: 36.5102,
      lng: -4.8860,
      precio: 850000,
      precioM2: 2833,
      antiguedad: 5,
      tipo: "Villa",
      plantas: 2,
      metrosConstruidos: 300,
      terreno: 1500,
      habitaciones: 4,
      banos: 4,
      descripcion: "Espectacular villa de lujo cerca de la playa. Diseño moderno con acabados de primera calidad. Piscina infinita y jardín mediterráneo.",
      orientacion: "Sur",
      anoConstruccion: 2019,
      estado: "Excelente estado",
      extras: ["Piscina", "Jardín", "Garaje", "Sistema domótico"],
      imagenes: ["assets/img/inicio1.jpeg", "assets/img/inicio2.jpeg", "assets/img/inicio3.jpeg", "assets/img/inicio4.jpeg"]
    },
    {
      titulo: "Casa adosada con garaje",
      direccion: "Calle de la Paz, 23",
      ciudad: "Valencia",
      provincia: "Valencia",
      cp: "46001",
      pais: "España",
      lat: 39.4699,
      lng: -0.3763,
      precio: 220000,
      precioM2: 1833,
      antiguedad: 8,
      tipo: "Adosada",
      plantas: 2,
      metrosConstruidos: 120,
      terreno: 200,
      habitaciones: 3,
      banos: 2,
      descripcion: "Casa adosada en urbanización tranquila. Muy bien comunicada y cerca de todos los servicios. Ideal para familias jóvenes.",
      orientacion: "Este",
      anoConstruccion: 2016,
      estado: "Muy buen estado",
      extras: ["Garaje", "Trastero", "Comunidad"],
      imagenes: ["assets/img/inicio5.jpeg", "assets/img/inicio6.jpeg"]
    },
    {
      titulo: "Piso reformado en zona residencial",
      direccion: "Paseo de la Castellana, 120",
      ciudad: "Madrid",
      provincia: "Madrid",
      cp: "28046",
      pais: "España",
      lat: 40.4378,
      lng: -3.6795,
      precio: 380000,
      precioM2: 4222,
      antiguedad: 15,
      tipo: "Piso",
      plantas: 1,
      metrosConstruidos: 90,
      terreno: 0,
      habitaciones: 2,
      banos: 1,
      descripcion: "Piso completamente reformado en edificio moderno. Muy luminoso y con excelentes calidades. Zona muy bien comunicada.",
      orientacion: "Sur",
      anoConstruccion: 2009,
      estado: "Reformado",
      extras: ["Ascensor", "Trastero", "Parking"],
      imagenes: ["assets/img/inicio7.jpeg", "assets/img/inicio8.jpeg", "assets/img/inicio1.jpeg"]
    },
    {
      titulo: "Casa rústica rehabilitada",
      direccion: "Camino de los Molinos, s/n",
      ciudad: "Segovia",
      provincia: "Segovia",
      cp: "40001",
      pais: "España",
      lat: 40.9429,
      lng: -4.1088,
      precio: 180000,
      precioM2: 900,
      antiguedad: 100,
      tipo: "Rústica",
      plantas: 2,
      metrosConstruidos: 200,
      terreno: 5000,
      habitaciones: 4,
      banos: 2,
      descripcion: "Encantadora casa rústica completamente rehabilitada manteniendo su carácter original. Chimenea, bodega y corral. Ideal para amantes del campo.",
      orientacion: "Sur-Oeste",
      anoConstruccion: 1920,
      estado: "Rehabilitada",
      extras: ["Chimenea", "Bodega", "Corral", "Pozo"],
      imagenes: ["assets/img/inicio2.jpeg", "assets/img/inicio3.jpeg", "assets/img/inicio4.jpeg"]
    },
    {
      titulo: "Estudio moderno en el centro",
      direccion: "Calle Gran Vía, 15",
      ciudad: "Barcelona",
      provincia: "Barcelona",
      cp: "08002",
      pais: "España",
      lat: 41.3851,
      lng: 2.1734,
      precio: 125000,
      precioM2: 4167,
      antiguedad: 3,
      tipo: "Estudio",
      plantas: 1,
      metrosConstruidos: 30,
      terreno: 0,
      habitaciones: 1,
      banos: 1,
      descripcion: "Estudio moderno y funcional en pleno centro de Barcelona. Perfecto para estudiantes o profesionales jóvenes. Muy bien comunicado.",
      orientacion: "Este",
      anoConstruccion: 2021,
      estado: "Nuevo",
      extras: ["Ascensor", "Trastero"],
      imagenes: ["assets/img/inicio5.jpeg", "assets/img/inicio6.jpeg"]
    },
    {
      titulo: "Chalet con piscina y jardín",
      direccion: "Urbanización Los Pinos, 7",
      ciudad: "Sevilla",
      provincia: "Sevilla",
      cp: "41001",
      pais: "España",
      lat: 37.3891,
      lng: -5.9845,
      precio: 320000,
      precioM2: 1600,
      antiguedad: 12,
      tipo: "Independiente",
      plantas: 2,
      metrosConstruidos: 200,
      terreno: 800,
      habitaciones: 4,
      banos: 3,
      descripcion: "Chalet independiente en urbanización privada. Piscina, jardín con césped y porche. Zona muy tranquila y familiar.",
      orientacion: "Sur",
      anoConstruccion: 2012,
      estado: "Muy buen estado",
      extras: ["Piscina", "Jardín", "Garaje", "Porche"],
      imagenes: ["assets/img/inicio7.jpeg", "assets/img/inicio8.jpeg", "assets/img/inicio1.jpeg", "assets/img/inicio2.jpeg"]
    },
    {
      titulo: "Duplex en zona exclusiva",
      direccion: "Avenida de la Constitución, 28",
      ciudad: "Bilbao",
      provincia: "Vizcaya",
      cp: "48001",
      pais: "España",
      lat: 43.2627,
      lng: -2.9253,
      precio: 275000,
      precioM2: 2292,
      antiguedad: 6,
      tipo: "Dúplex",
      plantas: 2,
      metrosConstruidos: 120,
      terreno: 0,
      habitaciones: 3,
      banos: 2,
      descripcion: "Dúplex moderno en zona exclusiva de Bilbao. Terraza privada y muy luminoso. Edificio con todas las comodidades.",
      orientacion: "Sur",
      anoConstruccion: 2018,
      estado: "Excelente estado",
      extras: ["Terraza", "Ascensor", "Trastero", "Parking"],
      imagenes: ["assets/img/inicio3.jpeg", "assets/img/inicio4.jpeg", "assets/img/inicio5.jpeg"]
    },
    {
      titulo: "Casa de campo con finca",
      direccion: "Camino de la Dehesa, km 5",
      ciudad: "Cáceres",
      provincia: "Cáceres",
      cp: "10001",
      pais: "España",
      lat: 39.4753,
      lng: -6.3724,
      precio: 195000,
      precioM2: 975,
      antiguedad: 20,
      tipo: "Finca",
      plantas: 1,
      metrosConstruidos: 200,
      terreno: 20000,
      habitaciones: 3,
      banos: 2,
      descripcion: "Casa de campo con finca de 2 hectáreas. Ideal para ganadería o agricultura. Agua y luz. Acceso asfaltado.",
      orientacion: "Sur",
      anoConstruccion: 2004,
      estado: "Buen estado",
      extras: ["Finca", "Pozo", "Nave", "Corral"],
      imagenes: ["assets/img/inicio6.jpeg", "assets/img/inicio7.jpeg"]
    },
    {
      titulo: "Piso con terraza en primera línea",
      direccion: "Paseo Marítimo, 42",
      ciudad: "Alicante",
      provincia: "Alicante",
      cp: "03001",
      pais: "España",
      lat: 38.3452,
      lng: -0.4810,
      precio: 290000,
      precioM2: 3222,
      antiguedad: 10,
      tipo: "Piso",
      plantas: 1,
      metrosConstruidos: 90,
      terreno: 0,
      habitaciones: 2,
      banos: 2,
      descripcion: "Piso con terraza en primera línea de playa. Vistas al mar. Muy luminoso y con excelente orientación. Zona muy tranquila.",
      orientacion: "Sur",
      anoConstruccion: 2014,
      estado: "Muy buen estado",
      extras: ["Terraza", "Vistas al mar", "Ascensor", "Parking"],
      imagenes: ["assets/img/inicio8.jpeg", "assets/img/inicio1.jpeg", "assets/img/inicio2.jpeg"]
    },
    {
      titulo: "Villa moderna con piscina",
      direccion: "Calle del Sol, 15",
      ciudad: "Málaga",
      provincia: "Málaga",
      cp: "29001",
      pais: "España",
      lat: 36.7213,
      lng: -4.4214,
      precio: 425000,
      precioM2: 2125,
      antiguedad: 4,
      tipo: "Villa",
      plantas: 2,
      metrosConstruidos: 200,
      terreno: 1000,
      habitaciones: 4,
      banos: 3,
      descripcion: "Villa moderna con diseño contemporáneo. Piscina climatizada y jardín con sistema de riego automático. Zona residencial exclusiva.",
      orientacion: "Sur",
      anoConstruccion: 2020,
      estado: "Excelente estado",
      extras: ["Piscina", "Jardín", "Garaje", "Domótica"],
      imagenes: ["assets/img/inicio3.jpeg", "assets/img/inicio4.jpeg", "assets/img/inicio5.jpeg", "assets/img/inicio6.jpeg"]
    },
    {
      titulo: "Ático con vistas panorámicas",
      direccion: "Calle de la Luna, 8",
      ciudad: "Valencia",
      provincia: "Valencia",
      cp: "46001",
      pais: "España",
      lat: 39.4699,
      lng: -0.3763,
      precio: 335000,
      precioM2: 3722,
      antiguedad: 7,
      tipo: "Ático",
      plantas: 1,
      metrosConstruidos: 90,
      terreno: 0,
      habitaciones: 3,
      banos: 2,
      descripcion: "Ático con terraza y vistas panorámicas a la ciudad. Muy luminoso y reformado. Edificio moderno con todas las comodidades.",
      orientacion: "Sur",
      anoConstruccion: 2017,
      estado: "Muy buen estado",
      extras: ["Terraza", "Vistas", "Ascensor", "Trastero"],
      imagenes: ["assets/img/inicio7.jpeg", "assets/img/inicio8.jpeg", "assets/img/inicio1.jpeg"]
    },
    {
      titulo: "Casa adosada con jardín",
      direccion: "Avenida de la Paz, 33",
      ciudad: "Zaragoza",
      provincia: "Zaragoza",
      cp: "50001",
      pais: "España",
      lat: 41.6488,
      lng: -0.8891,
      precio: 185000,
      precioM2: 1542,
      antiguedad: 11,
      tipo: "Adosada",
      plantas: 2,
      metrosConstruidos: 120,
      terreno: 150,
      habitaciones: 3,
      banos: 2,
      descripcion: "Casa adosada con jardín delantero y trasero. Urbanización tranquila con zonas comunes. Muy bien comunicada.",
      orientacion: "Este",
      anoConstruccion: 2013,
      estado: "Buen estado",
      extras: ["Jardín", "Garaje", "Trastero", "Comunidad"],
      imagenes: ["assets/img/inicio2.jpeg", "assets/img/inicio3.jpeg"]
    },
    {
      titulo: "Piso céntrico reformado",
      direccion: "Calle del Comercio, 12",
      ciudad: "Granada",
      provincia: "Granada",
      cp: "18001",
      pais: "España",
      lat: 37.1773,
      lng: -3.5986,
      precio: 165000,
      precioM2: 1833,
      antiguedad: 25,
      tipo: "Piso",
      plantas: 1,
      metrosConstruidos: 90,
      terreno: 0,
      habitaciones: 2,
      banos: 1,
      descripcion: "Piso céntrico completamente reformado. Muy bien ubicado cerca de todos los servicios. Ideal para parejas jóvenes.",
      orientacion: "Sur",
      anoConstruccion: 1999,
      estado: "Reformado",
      extras: ["Ascensor", "Trastero"],
      imagenes: ["assets/img/inicio4.jpeg", "assets/img/inicio5.jpeg", "assets/img/inicio6.jpeg"]
    },
    {
      titulo: "Chalet independiente de lujo",
      direccion: "Urbanización La Colina, 5",
      ciudad: "San Sebastián",
      provincia: "Guipúzcoa",
      cp: "20001",
      pais: "España",
      lat: 43.3183,
      lng: -1.9812,
      precio: 750000,
      precioM2: 2500,
      antiguedad: 3,
      tipo: "Independiente",
      plantas: 3,
      metrosConstruidos: 300,
      terreno: 1200,
      habitaciones: 5,
      banos: 4,
      descripcion: "Chalet independiente de lujo con diseño arquitectónico único. Piscina, jardín paisajístico y garaje para 3 coches. Zona exclusiva.",
      orientacion: "Sur",
      anoConstruccion: 2021,
      estado: "Nuevo",
      extras: ["Piscina", "Jardín", "Garaje", "Domótica", "Sala de cine"],
      imagenes: ["assets/img/inicio7.jpeg", "assets/img/inicio8.jpeg", "assets/img/inicio1.jpeg", "assets/img/inicio2.jpeg", "assets/img/inicio3.jpeg"]
    },
    {
      titulo: "Estudio funcional en el centro",
      direccion: "Calle de la Estrella, 7",
      ciudad: "Salamanca",
      provincia: "Salamanca",
      cp: "37001",
      pais: "España",
      lat: 40.9701,
      lng: -5.6635,
      precio: 95000,
      precioM2: 3167,
      antiguedad: 5,
      tipo: "Estudio",
      plantas: 1,
      metrosConstruidos: 30,
      terreno: 0,
      habitaciones: 1,
      banos: 1,
      descripcion: "Estudio funcional y moderno en el centro histórico. Perfecto para estudiantes o profesionales. Muy bien comunicado.",
      orientacion: "Este",
      anoConstruccion: 2019,
      estado: "Muy buen estado",
      extras: ["Ascensor"],
      imagenes: ["assets/img/inicio4.jpeg", "assets/img/inicio5.jpeg"]
    },
    {
      titulo: "Casa rústica con encanto",
      direccion: "Camino de los Olivos, 3",
      ciudad: "Toledo",
      provincia: "Toledo",
      cp: "45001",
      pais: "España",
      lat: 39.8628,
      lng: -4.0273,
      precio: 140000,
      precioM2: 700,
      antiguedad: 80,
      tipo: "Rústica",
      plantas: 2,
      metrosConstruidos: 200,
      terreno: 3000,
      habitaciones: 4,
      banos: 2,
      descripcion: "Casa rústica con mucho encanto rehabilitada manteniendo su esencia. Chimenea, bodega y corral. Ideal para escapadas rurales.",
      orientacion: "Sur",
      anoConstruccion: 1940,
      estado: "Rehabilitada",
      extras: ["Chimenea", "Bodega", "Corral", "Pozo"],
      imagenes: ["assets/img/inicio6.jpeg", "assets/img/inicio7.jpeg", "assets/img/inicio8.jpeg"]
    },
    {
      titulo: "Villa con piscina y jardín",
      direccion: "Avenida del Mediterráneo, 25",
      ciudad: "Tarragona",
      provincia: "Tarragona",
      cp: "43001",
      pais: "España",
      lat: 41.1189,
      lng: 1.2445,
      precio: 380000,
      precioM2: 1900,
      antiguedad: 6,
      tipo: "Villa",
      plantas: 2,
      metrosConstruidos: 200,
      terreno: 900,
      habitaciones: 4,
      banos: 3,
      descripcion: "Villa con piscina y jardín mediterráneo. Muy cerca de la playa. Zona tranquila y familiar. Perfecta para disfrutar del verano.",
      orientacion: "Sur",
      anoConstruccion: 2018,
      estado: "Excelente estado",
      extras: ["Piscina", "Jardín", "Garaje", "Porche"],
      imagenes: ["assets/img/inicio1.jpeg", "assets/img/inicio2.jpeg", "assets/img/inicio3.jpeg", "assets/img/inicio4.jpeg"]
    },
    {
      titulo: "Piso luminoso en zona céntrica",
      direccion: "Calle del Sol, 28",
      ciudad: "Córdoba",
      provincia: "Córdoba",
      cp: "14001",
      pais: "España",
      lat: 37.8882,
      lng: -4.7794,
      precio: 175000,
      precioM2: 1944,
      antiguedad: 18,
      tipo: "Piso",
      plantas: 1,
      metrosConstruidos: 90,
      terreno: 0,
      habitaciones: 3,
      banos: 2,
      descripcion: "Piso muy luminoso en el centro histórico. Reformado recientemente. Balcón con vistas. Ideal para vivir o invertir.",
      orientacion: "Sur",
      anoConstruccion: 2006,
      estado: "Reformado",
      extras: ["Balcón", "Ascensor", "Trastero"],
      imagenes: ["assets/img/inicio5.jpeg", "assets/img/inicio6.jpeg", "assets/img/inicio7.jpeg"]
    },
    {
      titulo: "Chalet con jardín y piscina",
      direccion: "Calle de los Pinos, 15",
      ciudad: "Valladolid",
      provincia: "Valladolid",
      cp: "47001",
      pais: "España",
      lat: 41.6523,
      lng: -4.7245,
      precio: 280000,
      precioM2: 1400,
      antiguedad: 10,
      tipo: "Independiente",
      plantas: 2,
      metrosConstruidos: 200,
      terreno: 600,
      habitaciones: 4,
      banos: 3,
      descripcion: "Chalet independiente con jardín y piscina. Zona residencial tranquila. Muy bien comunicado. Perfecto para familias.",
      orientacion: "Sur",
      anoConstruccion: 2014,
      estado: "Muy buen estado",
      extras: ["Piscina", "Jardín", "Garaje", "Trastero"],
      imagenes: ["assets/img/inicio8.jpeg", "assets/img/inicio1.jpeg", "assets/img/inicio2.jpeg"]
    },
    {
      titulo: "Ático con terraza panorámica",
      direccion: "Avenida de la Libertad, 42",
      ciudad: "Murcia",
      provincia: "Murcia",
      cp: "30001",
      pais: "España",
      lat: 37.9922,
      lng: -1.1307,
      precio: 310000,
      precioM2: 3444,
      antiguedad: 5,
      tipo: "Ático",
      plantas: 1,
      metrosConstruidos: 90,
      terreno: 0,
      habitaciones: 3,
      banos: 2,
      descripcion: "Ático exclusivo con terraza de 50m². Vistas panorámicas. Reformado con materiales de primera calidad. Zona premium.",
      orientacion: "Sur",
      anoConstruccion: 2019,
      estado: "Excelente estado",
      extras: ["Terraza", "Vistas", "Ascensor", "Parking"],
      imagenes: ["assets/img/inicio3.jpeg", "assets/img/inicio4.jpeg", "assets/img/inicio5.jpeg", "assets/img/inicio6.jpeg"]
    },
    {
      titulo: "Casa adosada con garaje",
      direccion: "Calle de la Paz, 8",
      ciudad: "Pamplona",
      provincia: "Navarra",
      cp: "31001",
      pais: "España",
      lat: 42.8125,
      lng: -1.6458,
      precio: 195000,
      precioM2: 1625,
      antiguedad: 9,
      tipo: "Adosada",
      plantas: 2,
      metrosConstruidos: 120,
      terreno: 180,
      habitaciones: 3,
      banos: 2,
      descripcion: "Casa adosada en urbanización con zonas comunes. Garaje y trastero. Muy bien comunicada. Ideal para familias jóvenes.",
      orientacion: "Este",
      anoConstruccion: 2015,
      estado: "Muy buen estado",
      extras: ["Garaje", "Trastero", "Comunidad", "Jardín"],
      imagenes: ["assets/img/inicio7.jpeg", "assets/img/inicio8.jpeg"]
    },
    {
      titulo: "Villa de lujo con piscina",
      direccion: "Camino de la Costa, 12",
      ciudad: "Santander",
      provincia: "Cantabria",
      cp: "39001",
      pais: "España",
      lat: 43.4623,
      lng: -3.8099,
      precio: 520000,
      precioM2: 2600,
      antiguedad: 4,
      tipo: "Villa",
      plantas: 2,
      metrosConstruidos: 200,
      terreno: 800,
      habitaciones: 4,
      banos: 3,
      descripcion: "Villa de lujo con piscina climatizada. Vistas al mar. Diseño moderno y acabados de primera calidad. Zona exclusiva.",
      orientacion: "Sur",
      anoConstruccion: 2020,
      estado: "Nuevo",
      extras: ["Piscina", "Jardín", "Garaje", "Domótica", "Vistas al mar"],
      imagenes: ["assets/img/inicio1.jpeg", "assets/img/inicio2.jpeg", "assets/img/inicio3.jpeg", "assets/img/inicio4.jpeg", "assets/img/inicio5.jpeg"]
    },
    {
      titulo: "Piso reformado en el centro",
      direccion: "Calle Mayor, 35",
      ciudad: "Logroño",
      provincia: "La Rioja",
      cp: "26001",
      pais: "España",
      lat: 42.4650,
      lng: -2.4456,
      precio: 145000,
      precioM2: 1611,
      antiguedad: 30,
      tipo: "Piso",
      plantas: 1,
      metrosConstruidos: 90,
      terreno: 0,
      habitaciones: 2,
      banos: 1,
      descripcion: "Piso completamente reformado en el casco antiguo. Muy luminoso. Cerca de todos los servicios. Perfecto para parejas.",
      orientacion: "Sur",
      anoConstruccion: 1994,
      estado: "Reformado",
      extras: ["Ascensor", "Trastero"],
      imagenes: ["assets/img/inicio6.jpeg", "assets/img/inicio7.jpeg", "assets/img/inicio8.jpeg"]
    },
    {
      titulo: "Finca rústica con viñedos",
      direccion: "Camino de los Viñedos, km 3",
      ciudad: "La Rioja",
      provincia: "La Rioja",
      cp: "26001",
      pais: "España",
      lat: 42.4650,
      lng: -2.4456,
      precio: 350000,
      precioM2: 7,
      antiguedad: 50,
      tipo: "Finca",
      plantas: 1,
      metrosConstruidos: 150,
      terreno: 50000,
      habitaciones: 3,
      banos: 2,
      descripcion: "Finca rústica con viñedos propios. Casa rehabilitada manteniendo su carácter. Bodega. Ideal para enoturismo.",
      orientacion: "Sur",
      anoConstruccion: 1970,
      estado: "Rehabilitada",
      extras: ["Viñedos", "Bodega", "Pozo", "Nave"],
      imagenes: ["assets/img/inicio1.jpeg", "assets/img/inicio2.jpeg", "assets/img/inicio3.jpeg"]
    },
    {
      titulo: "Estudio moderno en el centro",
      direccion: "Calle de la Estrella, 12",
      ciudad: "Oviedo",
      provincia: "Asturias",
      cp: "33001",
      pais: "España",
      lat: 43.3623,
      lng: -5.8448,
      precio: 88000,
      precioM2: 2933,
      antiguedad: 4,
      tipo: "Estudio",
      plantas: 1,
      metrosConstruidos: 30,
      terreno: 0,
      habitaciones: 1,
      banos: 1,
      descripcion: "Estudio moderno y funcional en el centro. Perfecto para estudiantes o profesionales. Muy bien comunicado.",
      orientacion: "Este",
      anoConstruccion: 2020,
      estado: "Nuevo",
      extras: ["Ascensor"],
      imagenes: ["assets/img/inicio4.jpeg", "assets/img/inicio5.jpeg"]
    },
    {
      titulo: "Chalet independiente de lujo",
      direccion: "Urbanización Los Robles, 5",
      ciudad: "Vigo",
      provincia: "Pontevedra",
      cp: "36201",
      pais: "España",
      lat: 42.2406,
      lng: -8.7207,
      precio: 420000,
      precioM2: 2100,
      antiguedad: 6,
      tipo: "Independiente",
      plantas: 2,
      metrosConstruidos: 200,
      terreno: 1000,
      habitaciones: 4,
      banos: 3,
      descripcion: "Chalet independiente de lujo con diseño arquitectónico único. Piscina, jardín y garaje. Zona exclusiva cerca del mar.",
      orientacion: "Sur",
      anoConstruccion: 2018,
      estado: "Excelente estado",
      extras: ["Piscina", "Jardín", "Garaje", "Domótica"],
      imagenes: ["assets/img/inicio6.jpeg", "assets/img/inicio7.jpeg", "assets/img/inicio8.jpeg", "assets/img/inicio1.jpeg"]
    },
    {
      titulo: "Piso con balcón en primera línea",
      direccion: "Paseo Marítimo, 25",
      ciudad: "Gijón",
      provincia: "Asturias",
      cp: "33201",
      pais: "España",
      lat: 43.5453,
      lng: -5.6619,
      precio: 225000,
      precioM2: 2500,
      antiguedad: 12,
      tipo: "Piso",
      plantas: 1,
      metrosConstruidos: 90,
      terreno: 0,
      habitaciones: 2,
      banos: 2,
      descripcion: "Piso con balcón en primera línea de playa. Vistas al mar. Muy luminoso. Zona tranquila y bien comunicada.",
      orientacion: "Sur",
      anoConstruccion: 2012,
      estado: "Muy buen estado",
      extras: ["Balcón", "Vistas al mar", "Ascensor", "Parking"],
      imagenes: ["assets/img/inicio2.jpeg", "assets/img/inicio3.jpeg", "assets/img/inicio4.jpeg"]
    },
    {
      titulo: "Casa rústica con encanto",
      direccion: "Camino de la Dehesa, 7",
      ciudad: "Cáceres",
      provincia: "Cáceres",
      cp: "10001",
      pais: "España",
      lat: 39.4753,
      lng: -6.3724,
      precio: 125000,
      precioM2: 625,
      antiguedad: 60,
      tipo: "Rústica",
      plantas: 2,
      metrosConstruidos: 200,
      terreno: 4000,
      habitaciones: 4,
      banos: 2,
      descripcion: "Casa rústica con mucho encanto rehabilitada. Chimenea, bodega y corral. Ideal para amantes del campo y la tranquilidad.",
      orientacion: "Sur",
      anoConstruccion: 1960,
      estado: "Rehabilitada",
      extras: ["Chimenea", "Bodega", "Corral", "Pozo"],
      imagenes: ["assets/img/inicio5.jpeg", "assets/img/inicio6.jpeg", "assets/img/inicio7.jpeg"]
    },
    {
      titulo: "Dúplex moderno con terraza",
      direccion: "Avenida de la Constitución, 18",
      ciudad: "Bilbao",
      provincia: "Vizcaya",
      cp: "48001",
      pais: "España",
      lat: 43.2627,
      lng: -2.9253,
      precio: 290000,
      precioM2: 2417,
      antiguedad: 7,
      tipo: "Dúplex",
      plantas: 2,
      metrosConstruidos: 120,
      terreno: 0,
      habitaciones: 3,
      banos: 2,
      descripcion: "Dúplex moderno con terraza privada. Muy luminoso. Edificio nuevo con todas las comodidades. Zona exclusiva.",
      orientacion: "Sur",
      anoConstruccion: 2017,
      estado: "Muy buen estado",
      extras: ["Terraza", "Ascensor", "Trastero", "Parking"],
      imagenes: ["assets/img/inicio8.jpeg", "assets/img/inicio1.jpeg", "assets/img/inicio2.jpeg"]
    },
    {
      titulo: "Villa con piscina y jardín",
      direccion: "Calle del Mar, 22",
      ciudad: "Almería",
      provincia: "Almería",
      cp: "04001",
      pais: "España",
      lat: 36.8381,
      lng: -2.4597,
      precio: 380000,
      precioM2: 1900,
      antiguedad: 8,
      tipo: "Villa",
      plantas: 2,
      metrosConstruidos: 200,
      terreno: 900,
      habitaciones: 4,
      banos: 3,
      descripcion: "Villa con piscina y jardín mediterráneo. Muy cerca de la playa. Zona tranquila. Perfecta para disfrutar del clima.",
      orientacion: "Sur",
      anoConstruccion: 2016,
      estado: "Excelente estado",
      extras: ["Piscina", "Jardín", "Garaje", "Porche"],
      imagenes: ["assets/img/inicio3.jpeg", "assets/img/inicio4.jpeg", "assets/img/inicio5.jpeg", "assets/img/inicio6.jpeg"]
    },
    {
      titulo: "Piso céntrico reformado",
      direccion: "Calle del Comercio, 8",
      ciudad: "Granada",
      provincia: "Granada",
      cp: "18001",
      pais: "España",
      lat: 37.1773,
      lng: -3.5986,
      precio: 155000,
      precioM2: 1722,
      antiguedad: 25,
      tipo: "Piso",
      plantas: 1,
      metrosConstruidos: 90,
      terreno: 0,
      habitaciones: 2,
      banos: 1,
      descripcion: "Piso céntrico completamente reformado. Muy bien ubicado cerca de todos los servicios. Ideal para parejas jóvenes.",
      orientacion: "Sur",
      anoConstruccion: 1999,
      estado: "Reformado",
      extras: ["Ascensor", "Trastero"],
      imagenes: ["assets/img/inicio7.jpeg", "assets/img/inicio8.jpeg", "assets/img/inicio1.jpeg"]
    },
    {
      titulo: "Chalet con piscina y jardín",
      direccion: "Urbanización La Colina, 12",
      ciudad: "San Sebastián",
      provincia: "Guipúzcoa",
      cp: "20001",
      pais: "España",
      lat: 43.3183,
      lng: -1.9812,
      precio: 680000,
      precioM2: 2267,
      antiguedad: 3,
      tipo: "Independiente",
      plantas: 3,
      metrosConstruidos: 300,
      terreno: 1100,
      habitaciones: 5,
      banos: 4,
      descripcion: "Chalet independiente de lujo con diseño único. Piscina, jardín paisajístico. Zona exclusiva con vistas al mar.",
      orientacion: "Sur",
      anoConstruccion: 2021,
      estado: "Nuevo",
      extras: ["Piscina", "Jardín", "Garaje", "Domótica", "Vistas"],
      imagenes: ["assets/img/inicio2.jpeg", "assets/img/inicio3.jpeg", "assets/img/inicio4.jpeg", "assets/img/inicio5.jpeg", "assets/img/inicio6.jpeg"]
    },
    {
      titulo: "Estudio funcional en el centro",
      direccion: "Calle de la Estrella, 5",
      ciudad: "Salamanca",
      provincia: "Salamanca",
      cp: "37001",
      pais: "España",
      lat: 40.9701,
      lng: -5.6635,
      precio: 92000,
      precioM2: 3067,
      antiguedad: 5,
      tipo: "Estudio",
      plantas: 1,
      metrosConstruidos: 30,
      terreno: 0,
      habitaciones: 1,
      banos: 1,
      descripcion: "Estudio funcional y moderno en el centro histórico. Perfecto para estudiantes o profesionales. Muy bien comunicado.",
      orientacion: "Este",
      anoConstruccion: 2019,
      estado: "Muy buen estado",
      extras: ["Ascensor"],
      imagenes: ["assets/img/inicio7.jpeg", "assets/img/inicio8.jpeg"]
    },
    {
      titulo: "Casa rústica rehabilitada",
      direccion: "Camino de los Olivos, 8",
      ciudad: "Toledo",
      provincia: "Toledo",
      cp: "45001",
      pais: "España",
      lat: 39.8628,
      lng: -4.0273,
      precio: 135000,
      precioM2: 675,
      antiguedad: 80,
      tipo: "Rústica",
      plantas: 2,
      metrosConstruidos: 200,
      terreno: 3500,
      habitaciones: 4,
      banos: 2,
      descripcion: "Casa rústica con mucho encanto rehabilitada manteniendo su esencia. Chimenea, bodega y corral. Ideal para escapadas.",
      orientacion: "Sur",
      anoConstruccion: 1940,
      estado: "Rehabilitada",
      extras: ["Chimenea", "Bodega", "Corral", "Pozo"],
      imagenes: ["assets/img/inicio1.jpeg", "assets/img/inicio2.jpeg", "assets/img/inicio3.jpeg"]
    },
    {
      titulo: "Villa con piscina y jardín",
      direccion: "Avenida del Mediterráneo, 30",
      ciudad: "Tarragona",
      provincia: "Tarragona",
      cp: "43001",
      pais: "España",
      lat: 41.1189,
      lng: 1.2445,
      precio: 365000,
      precioM2: 1825,
      antiguedad: 6,
      tipo: "Villa",
      plantas: 2,
      metrosConstruidos: 200,
      terreno: 850,
      habitaciones: 4,
      banos: 3,
      descripcion: "Villa con piscina y jardín mediterráneo. Muy cerca de la playa. Zona tranquila y familiar. Perfecta para el verano.",
      orientacion: "Sur",
      anoConstruccion: 2018,
      estado: "Excelente estado",
      extras: ["Piscina", "Jardín", "Garaje", "Porche"],
      imagenes: ["assets/img/inicio4.jpeg", "assets/img/inicio5.jpeg", "assets/img/inicio6.jpeg", "assets/img/inicio7.jpeg"]
    },
    {
      titulo: "Ático con terraza y vistas",
      direccion: "Calle de la Luna, 15",
      ciudad: "Valencia",
      provincia: "Valencia",
      cp: "46001",
      pais: "España",
      lat: 39.4699,
      lng: -0.3763,
      precio: 340000,
      precioM2: 3778,
      antiguedad: 7,
      tipo: "Ático",
      plantas: 1,
      metrosConstruidos: 90,
      terreno: 0,
      habitaciones: 3,
      banos: 2,
      descripcion: "Ático con terraza y vistas panorámicas a la ciudad. Muy luminoso y reformado. Edificio moderno con todas las comodidades.",
      orientacion: "Sur",
      anoConstruccion: 2017,
      estado: "Muy buen estado",
      extras: ["Terraza", "Vistas", "Ascensor", "Trastero"],
      imagenes: ["assets/img/inicio8.jpeg", "assets/img/inicio1.jpeg", "assets/img/inicio2.jpeg"]
    },
    {
      titulo: "Casa adosada con jardín",
      direccion: "Avenida de la Paz, 40",
      ciudad: "Zaragoza",
      provincia: "Zaragoza",
      cp: "50001",
      pais: "España",
      lat: 41.6488,
      lng: -0.8891,
      precio: 190000,
      precioM2: 1583,
      antiguedad: 11,
      tipo: "Adosada",
      plantas: 2,
      metrosConstruidos: 120,
      terreno: 160,
      habitaciones: 3,
      banos: 2,
      descripcion: "Casa adosada con jardín delantero y trasero. Urbanización tranquila con zonas comunes. Muy bien comunicada.",
      orientacion: "Este",
      anoConstruccion: 2013,
      estado: "Buen estado",
      extras: ["Jardín", "Garaje", "Trastero", "Comunidad"],
      imagenes: ["assets/img/inicio3.jpeg", "assets/img/inicio4.jpeg"]
    },
    {
      titulo: "Piso con terraza en primera línea",
      direccion: "Paseo Marítimo, 50",
      ciudad: "Alicante",
      provincia: "Alicante",
      cp: "03001",
      pais: "España",
      lat: 38.3452,
      lng: -0.4810,
      precio: 305000,
      precioM2: 3389,
      antiguedad: 10,
      tipo: "Piso",
      plantas: 1,
      metrosConstruidos: 90,
      terreno: 0,
      habitaciones: 2,
      banos: 2,
      descripcion: "Piso con terraza en primera línea de playa. Vistas al mar. Muy luminoso y con excelente orientación. Zona muy tranquila.",
      orientacion: "Sur",
      anoConstruccion: 2014,
      estado: "Muy buen estado",
      extras: ["Terraza", "Vistas al mar", "Ascensor", "Parking"],
      imagenes: ["assets/img/inicio5.jpeg", "assets/img/inicio6.jpeg", "assets/img/inicio7.jpeg"]
    },
    {
      titulo: "Villa moderna con piscina",
      direccion: "Calle del Sol, 20",
      ciudad: "Málaga",
      provincia: "Málaga",
      cp: "29001",
      pais: "España",
      lat: 36.7213,
      lng: -4.4214,
      precio: 440000,
      precioM2: 2200,
      antiguedad: 4,
      tipo: "Villa",
      plantas: 2,
      metrosConstruidos: 200,
      terreno: 950,
      habitaciones: 4,
      banos: 3,
      descripcion: "Villa moderna con diseño contemporáneo. Piscina climatizada y jardín con sistema de riego automático. Zona residencial exclusiva.",
      orientacion: "Sur",
      anoConstruccion: 2020,
      estado: "Excelente estado",
      extras: ["Piscina", "Jardín", "Garaje", "Domótica"],
      imagenes: ["assets/img/inicio8.jpeg", "assets/img/inicio1.jpeg", "assets/img/inicio2.jpeg", "assets/img/inicio3.jpeg"]
    }
  ];

  getCasas(): Casa[] {
    return this.casas.map((casa, index) => ({ ...casa, id: `casa-${index + 1}` }));
  }

  getCasaById(id: string): Casa | undefined {
    const index = parseInt(id.split('-')[1]) - 1;
    if (index >= 0 && index < this.casas.length) {
      return { ...this.casas[index], id: `casa-${index + 1}` };
    }
    return undefined;
  }
}
